version: "1.0"
stages:
  - "clone"
  - "build"
  - "metadata"
  - "gitops"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "andrew-collett/gitops-app-source-code"
    revision: '${{CF_REVISION}}'
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "tolrendor-software/simple-web-app"
    working_directory: "${{clone}}"
    tags:
    - "latest"
    - '${{CF_SHORT_REVISION}}'
    dockerfile: "Dockerfile"
    stage: "build"
    registry: ecr-tolrendor-software  
  enrich-image:
    title: Add PR info
    type: image-enricher
    stage: "metadata"
    arguments:
      IMAGE:  868143226472.dkr.ecr.eu-west-1.amazonaws.com/tolrendor-software/simple-web-app:latest
      BRANCH: '${{CF_BRANCH}}'
      REPO: 'andrew-collett/gitops-app-source-code'
      GIT_PROVIDER_NAME: andrew-collett
  clone_gitops:
    title: cloning gitops repo
    type: git-clone
    arguments:
      repo: 'andrew-collett/gitops-kubernetes-configuration'
      revision: 'master'
    stage: "gitops"
    when:
      branch:
        only:
          - master    
  change_manifest:
    title: "Update k8s manifest"
    image: "mikefarah/yq" # The image in which command will be executed
    commands:
      - yq eval -i 'spec.template.spec.containers[0].image = "d868143226472.dkr.ecr.eu-west-1.amazonaws.com/tolrendor-software/simple-web-app:${{CF_SHORT_REVISION}}"' deployment.yaml
      - cat deployment.yml
    working_directory: "${{clone_gitops}}" 
    stage: "gitops"
    when:
      branch:
        only:
          - master 
  commit_and_push:
    title: Commit manifest
    type: git-commit
    stage: "gitops"
    arguments:
      repo: 'andrew-collett/gitops-kubernetes-configuration'
      git: andrew-collett
      working_directory: '/codefresh/volume/gitops-kubernetes-configuration'
      commit_message: Updated manifest
      git_user_name: andrew-collett
      git_user_email: andrew.collett@me.com
    when:
      branch:
        only:
          - master      
